version: '3.7'

services:
  ct-db:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    volumes:
      - ct-data:/var/lib/mysql
    ports:
      - 3306:3306
      
volumes:
  ct-data: {}